### ISSUE TITLE
Question: How to use Scheduled Tasks ?

### ISSUE THREAD

**Issue by nicodel** [Monogramm/docker-dolibarr#45]
Hi,

I use your docker image (apache 9.0) of Dolibarr and it works perfectly. It is connected to a MariaDB image for the DB.

I was trying to configure scheduled tasks, like database dumps for backups, and I cannot get it to be scheduled. When ran manually, it works and a dump is generated.

From what I understand I should add the following line to the cron tab (useing `crontab -e`):
```
*/5 * * * * pathtoscript/scripts/cron/cron_run_jobs.php <key> <user> > /var/www/documents/cron_run_jobs.php.log
```
But as `cron` is not installed on the image, it is not possible.

Do you know how should I do this ?

Thanks for your help.

**Comment by madmath03** [comment]
Hello @nicodel,

I'm glad to see this image is working fine for you 😃 
Well, I guess the answer is simple : we need to add cron to this image.

That shouldn't take long, so you should be able to retrieve the latest image with cron today or tomorrow (depends on the time needed by dockerhub to rebuild the images).

For your convenience though, I suggest you to mount /etc/crontab locally so that you will not lose your crontab configuration when dropping then restarting your container.

**Comment by nicodel** [comment]
Thank you very much for your answer and quick fix.

**Comment by nicodel** [comment]
Arf, `cron` needs an editor, and it seems that the image does not contain any.

Can I do a pull request to install `vi` on the image ?
