### ISSUE TITLE
DOLI_DB_PORT is mandatory

### ISSUE THREAD

**Issue by daamien** [Monogramm/docker-dolibarr#6]
Hi!

Thanks for this docker image it is really helpfull. 

I have problem because the docker-compose you're giving does not have a DOLI_DB_PORT env variable defined

This produces the following error:

```
Parse error: syntax error, unexpected ';' in /var/www/html/install/install.forced.php on line 29
```

In `install.forced.php` the line looks like this
```
/** @var int Database server port */
$force_install_port = ;
```

**Comment by daamien** [comment]
same for `DOLI_DB_TYPE`

**Comment by madmath03** [comment]
Hi!

I'm glad you like this docker image :blush:

Indeed, we were so focused on providing more flexibility than the other docker images that we always used it by setting all fields and missed the mandatory parameters. Thanks for reporting that.

Since Dolibarr is mostly used with MySQL, we will set properties to MySQL default values and secure `install.forced.php` for empty values.
Do no hesitate if you have a different point of view on how to fix this.
